AlmasB/FXGL

- src/main/java/com/almasb/fxgl/physics/PhysicsComponent.java
Some methods I am using in my project
> add apply LinearImpulse / Force / ForceToCenter / AngularImpulse / Torque methods to PhysicsComponent

- fxgl-samples/src/main/java/s09advanced/NoiseSample.java
- fxgl-samples/src/main/java/s10miscellaneous/JointSample.java
- fxgl/src/main/java/com/almasb/fxgl/ai/utils/random/TriangularFloatDistribution.java
- fxgl/src/main/java/com/almasb/fxgl/ai/utils/random/TriangularIntegerDistribution.java
- fxgl/src/main/java/com/almasb/fxgl/ai/utils/random/UniformFloatDistribution.java
- fxgl/src/main/java/com/almasb/fxgl/core/math/FXGLMath.java
- fxgl/src/main/java/com/almasb/fxgl/core/math/Vec2.java
- fxgl/src/main/kotlin/com/almasb/fxgl/core/math/PerlinNoiseGenerator.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/devtools/profiling/Profiler.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/scene/Viewport.kt
> use double instead of float as main numerical type in FXGLMath

- fxgl/src/main/kotlin/com/almasb/fxgl/texture/ColoredTexture.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/texture/Texture.kt
- fxgl/src/test/kotlin/com/almasb/fxgl/texture/ColoredTextureTest.kt
Dear Almas,
The changes you requested: A new ColoredTexture class.
> 468 // Add ColoredTexture

- fxgl/src/main/java/com/almasb/fxgl/entity/component/BoundingBoxComponent.java
> BoundingBoxComponent deep copy

- fxgl/src/main/java/com/almasb/fxgl/app/AppStateMachine.java
- fxgl/src/main/java/com/almasb/fxgl/app/GameApplication.java
> Null issues resolved

- fxgl-base/src/main/kotlin/com/almasb/fxgl/animation/ParallelAnimation.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/animation/SequentialAnimation.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/app/FXGL.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/app/PauseMenuSubState.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/asset/AssetLoader.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/core/logging/Logger.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/entity/GameWorld.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/entity/view/ParallaxBackgroundView.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/entity/view/ScrollingBackgroundView.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/event/EventBus.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/event/EventTrigger.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/gameplay/achievement/AchievementManager.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/gameplay/qte/QTEProvider.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/gameplay/rpg/quest/Quest.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/gameplay/rpg/quest/QuestObjective.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/input/Input.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/parser/tiled/TiledLayerView.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/texture/ColoredTexture.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/texture/Texture.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/extra/ai/goap/GoapControl.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/extra/ui/WheelMenu.kt
Refactored assertions to use check and require instead of manually checks.
requireNotNull is only used where the returnValue isn't used.
> assertions now use built-in functions

- fxgl-base/src/main/kotlin/com/almasb/fxgl/app/MainWindow.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/entity/GameWorld.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/input/Input.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/net/FXGLNet.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/extra/algorithm/VoronoiSubdivision.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/extra/entity/effect/EffectComponent.kt
replace contains with infix call in
> use in instead of contains

- fxgl-base/src/main/kotlin/com/almasb/fxgl/ai/AIControl.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/app/DialogSubState.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/asset/AssetLoader.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/core/collection/PropertyMap.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/devtools/Console.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/entity/animation/AnimationBuilder.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/entity/components/BoundingBoxComponent.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/gameplay/cutscene/JRPGCutsceneState.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/gameplay/notification/NotificationServiceProvider.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/input/Input.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/io/serialization/Bundle.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/net/FXGLNet.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/parser/KVFile.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/parser/text/TextLevelParser.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/parser/tiled/TMXParser.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/saving/SaveFile.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/time/FPSCounter.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/ui/FXGLDialogFactory.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/util/Credits.kt
- fxgl-base/src/main/kotlin/com/almasb/fxgl/util/SystemPropertyKeyGen.kt
- fxgl-base/src/test/kotlin/com/almasb/fxgl/asset/AssetLoaderTest.kt
- fxgl-base/src/test/kotlin/com/almasb/fxgl/physics/HitBoxTest.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/extra/ai/goap/FSM.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/extra/ai/goap/GoapAgent.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/extra/ai/goap/State.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/extra/algorithm/PlatformerLevelGenerator.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/extra/algorithm/VoronoiSubdivision.kt
- fxgl/src/main/kotlin/com/almasb/fxgl/extra/entity/effects/WobbleEffect.kt
Use kotlin-methods instead of java-methods where possible.
> prioritize kotlin imports

- fxgl/src/main/resources/assets/properties/languages/hungarian.properties
Add missing hungarian translation.
> Hungarian language support

- fxgl-core/src/test/kotlin/com/almasb/fxgl/core/math/Vec2Test.kt
Now covering 100%:
- _minToOut_
- _maxToOut_
- _getLengthAndNormalise_
- _equals_
> Added tests to cover Vec2 functionality.

- fxgl/src/main/kotlin/com/almasb/fxgl/dsl/components/LiftComponent.kt
Hi!
Let me know if this is how you intended it to be refactored.
I wrapped all related liftdata fields into one a "LiftData" class.
> Issue #657 LiftComponent refactor

- fxgl-core/src/main/java/com/almasb/fxgl/core/reflect/ReflectionUtils.java
Hi.
As discussed in the Issue #673 here is the PR which solves that issue.
Tests are still passing.
> Fix for Issue #673

- fxgl/src/main/kotlin/com/almasb/fxgl/app/Settings.kt
- fxgl/src/test/kotlin/com/almasb/fxgl/app/GameSettingsTest.kt
**What this PR does**
Adds two new methods to **Settings.kt** as per the request in issue #669 
**Dev Notes**
1. Local build successful
2. No Unit tests for new code
> Add set width and height from ratio methods #669

- fxgl-samples/src/main/java/sandbox/PlatformerSample.java
- fxgl/src/main/kotlin/com/almasb/fxgl/dsl/components/FollowComponent.kt
Added support to allow a Duration amount of time to be set as delay for FollowComponent.
A demo implementation is done in PlatformerSample.
> Respond to Issue #678

- fxgl-input/src/main/kotlin/com/almasb/fxgl/input/virtual/VirtualInput.kt
> Enlarged the virtual controller views #650

- fxgl-entity/src/main/kotlin/com/almasb/fxgl/entity/level/tiled/TMXLevelLoader.kt
Automatically add IDComponent to entities parsed via TiledMap.
> Automatically add IDComponent to entities parsed via TiledMap.

- fxgl/src/main/kotlin/com/almasb/fxgl/app/Engine.kt
Add Java vendor, Operating System name, Operating System version, and Operating System architecture.
Issue #766
> #766 - Log detailed OS info.

- fxgl-samples/src/main/java/sandbox/customization/MenuSample.java
- fxgl/src/main/resources/fxglassets/ui/css/fxgl_dark.css
Change checkbox style to have a white background.
> Issue #765 fullscreen check box

- fxgl-ui/src/main/java/com/almasb/fxgl/ui/ProgressBar.java
Allow access to backgroundBar and innerBar Rectangle objects so that they may be customised.
Signed-off-by: ross-holloway94 <ross.holloway94+github@gmail.com>
> Issue #785 progressbar customization

- fxgl/src/main/kotlin/com/almasb/fxgl/dsl/components/OffscreenInvisibleComponent.kt
- fxgl/src/test/kotlin/com/almasb/fxgl/dsl/components/OffscreenInvisibleComponentTest.kt
I had time to do one more easy task. Similar to OffscreenCleanComponent.
> implemented OffscreenInvisibleComponent, resolves #838

- fxgl-ai/src/main/java/com/almasb/fxgl/pathfinding/Grid.java
- fxgl-ai/src/test/java/com/almasb/fxgl/pathfinding/GridTest.java
add properties cellWidth and cellHeight to Grid<>;
add new constructor which takes cellWidth and cellHeight along with other parameters;
add tests to check that new constructor and getters are working as intended;
closes #706
> #706 Grid<> should have extra fields: cellWidth and cellHeight of type int

- fxgl-core/src/main/kotlin/com/almasb/fxgl/core/collection/PropertyMap.kt
- fxgl-core/src/test/kotlin/com/almasb/fxgl/core/collection/PropertyMapTest.kt
add forEach function to PropertyMap which iterate through all elements and call BiConsumer on each of them
add test for forEach function to check its working as intended 
closes #699
> #699 Add PropertyMap::forEach

- fxgl-core/src/test/kotlin/com/almasb/fxgl/core/concurrent/ConcurrencyTest.kt
- fxgl/src/test/kotlin/com/almasb/fxgl/app/GameApplicationTest.kt
- fxgl/src/test/kotlin/com/almasb/fxgl/app/services/IOTaskExecutorServiceTest.kt
Replace assertTimeout in tests with assertTimeoutPreemptively
closes #743
> #743 Replace assertTimeout in tests with assertTimeoutPreemptively

- fxgl/src/main/kotlin/com/almasb/fxgl/dev/profiling/ProfilerService.kt
change algorithm of counting currentTimeTook - now its average frame time of the last 30 frames.
closes #806
> #806 ProfilerService: currentTimeTook should be buffered over several frames

- fxgl-samples/src/main/java/sandbox/view/WobbleEffectSample.java
- fxgl/src/main/kotlin/com/almasb/fxgl/dsl/effects/WobbleEffect.kt
refactor Wobble effect to make it more pixel perfect.  
closes #797
> #797 refactor Wobble effect to make it more pixel perfect.

- fxgl/src/main/kotlin/com/almasb/fxgl/dsl/EntityBuilder.kt
- fxgl/src/test/kotlin/com/almasb/fxgl/dsl/EntityBuilderTest.kt
Add EntityBuilder::anchorFromCenter along with test
closes #854
> #854 Add EntityBuilder::anchorFromCenter

- fxgl-ai/src/main/java/com/almasb/fxgl/pathfinding/astar/AStarMoveComponent.java
- fxgl-ai/src/test/kotlin/com/almasb/fxgl/pathfinding/astar/AStarMoveComponentTest.kt
- fxgl-samples/src/main/java/sandbox/ai/pathfinding/MassUnitsRTSSample.java
Resolves #844
I added the functionality and tests as described in the issue. 
Let me know if I can make improvements.
I created this PR in the context of the [Hacktoberfest](https://hacktoberfest.digitalocean.com/). So it would be nice if you could label the PR as `hacktoberfest-accepted` if you appreciate my contribution.
> Implement AStarMoveComponent::stopMovement

- fxgl-media/src/main/kotlin/com/almasb/fxgl/audio/AudioPlayer.kt
Adds some methods to pause/stop/resume all sounds and music that is currently playing. Useful for when you need to pause and turn off all noises and then need to resume any active sounds when unpausing.
> Add ability to stop all sounds and music

- fxgl-samples/src/main/kotlin/sandbox/subscene/AboutSubScene.kt
- fxgl-samples/src/main/kotlin/sandbox/subscene/MainSubScene.kt
- fxgl-samples/src/main/kotlin/sandbox/subscene/NavigateEvent.kt
- fxgl-samples/src/main/kotlin/sandbox/subscene/OptionsSubScene.kt
- fxgl-samples/src/main/kotlin/sandbox/subscene/PlaySubScene.kt
- fxgl-samples/src/main/kotlin/sandbox/subscene/SubSceneSampleApp.kt
- fxgl-samples/src/main/kotlin/sandbox/subscene/UIConstants.kt
A basic demo showing how to create subscenes and navigate between them.
> Subscene demo code added.

- fxgl-animation/src/main/kotlin/com/almasb/fxgl/animation/AnimatedValue.kt
- fxgl-animation/src/test/kotlin/com/almasb/fxgl/animation/AnimatedValueTest.kt
I have made the changes you suggest me and I also add a test for each class.
> Dublication Fixed in AnimatedValue.kt #925
